### ISSUE TITLE
Module Error how to deal it ?

### ISSUE THREAD

**Issue by Cccccc2018** [bikz05/digit-recognition#7]
When I try to test the classifier, run the `performRecognition.py` script, I faced this problem, and I have no idea how to deal with that. I tried to run it in python 2 and python 3,  it all has problems, hope someone can help me, thank you!

pi@raspberrypi:~/digit-recognition $ python performRecognition.py -c digits_cls.pkl -i photo_1.jpg
Traceback (most recent call last):
  File "performRecognition.py", line 51, in <module>
    nbr = clf.predict(roi_hog_fd)
  File "/usr/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 228, in predict
    return self.classes_[indices]
  File "/usr/lib/python2.7/dist-packages/sklearn/svm/base.py", line 709, in classes_
    return self._enc.classes_
AttributeError: 'LinearSVC' object has no attribute '_enc'

**Comment by moFang222** [comment]
@Cccccc2018  I encounter the same issue. Have you fixed it?
