### ISSUE TITLE
Error will running generateclassifier.py

### ISSUE THREAD

**Issue by nethajinirmal13** [bikz05/digit-recognition#8]
Traceback (most recent call last):
  File "generateClassifier.py", line 13, in <module>
    dataset = datasets.fetch_mldata("MNIST Original")
  File "/usr/lib/python2.7/dist-packages/sklearn/datasets/mldata.py", line 142, in fetch_mldata
    mldata_url = urlopen(urlname)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by TowsifAhamed** [comment]
Use mnist_784 instead of MNIST Original. You can see [digit-recognition](https://github.com/1ronMan17/digit-recognition/) to use it in python3.
#13
